name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # Add plausible analytics, curious how many people
      # visit each demo
      - name: Add Stats
        run: |
          sed -i.bk "s/<\/body>/<script defer data-domain='willusher.io' src='https:\/\/pan.wushernet.com\/js\/script.js'><\/script><\/body>/" index.html

      - name: Build App
        run: |
          npm i
          npm run build

      - name: Upload Web App Dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/dist

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

